//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemicalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int msg_id { get; set; }
        public int msg_user_id { get; set; }
        public string msg_content { get; set; }
        public string msg_time { get; set; }
        public string reply_content { get; set; }
        public string reply_time { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
