//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemicalManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIMSDBEntities : DbContext
    {
        public CIMSDBEntities()
            : base("name=CIMSDBEntities")
        {
            this.Database.Connection.ConnectionString += ";password=000000";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Industry> Industry { get; set; }
        public virtual DbSet<Meterial> Meterial { get; set; }
        public virtual DbSet<View_PDF> View_PDF { get; set; }
        public virtual DbSet<User_Group> User_Group { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<View_Msg> View_Msg { get; set; }
        public virtual DbSet<PDF> PDF { get; set; }
    }
}
