//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemicalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PDF
    {
        public int pdf_id { get; set; }
        public string pdf_name { get; set; }
        public string pdf_uploadtime { get; set; }
        public string met_name { get; set; }
        public string comp_name { get; set; }
        public string ind_name { get; set; }
    }
}
